### ISSUE TITLE
Optimize images 

### ISSUE THREAD

**Issue by Khanhtran47** [Khanhtran47/remix-movie#101]
- [ ] https://github.com/Josh-McFarlin/remix-image
- [ ] lazy-loading images

**Comment by Khanhtran47** [comment]
@ctuanle cái remix-image, t định xài cái hook của hấn để lm responsive file ảnh cho đúng với cái size hiển thị trên web ý, đều nản vãi, cái hook của hấn bắt buộc phải bỏ vào img, k chạy để lấy link đc, với thẻ Image bên Nextui k chèn props vào đc, nó cứ bị gì ý -.-

**Comment by ctuanle** [comment]
> cái remix-image, t định xài cái hook của hấn để lm responsive file ảnh cho đúng với cái size hiển thị trên web ý, đều nản vãi, cái hook của hấn bắt buộc phải bỏ vào img, k chạy để lấy link đc

@Khanhtran47  cái repo đó được có gần 200 commits à, code lại 1 cái cho tiện 🤖



> với thẻ Image bên Nextui k chèn props vào đc, nó cứ bị gì ý -.-

thử bỏ trong 1 cái wrapper xem thử

**Comment by Khanhtran47** [comment]
@ctuanle kiểu cái Image bên Nextui ý hấn render ra 1 thẻ div bao quanh 1 thẻ img ở bên trong rứa, chắc mò cái ni sau chơ phức tạp vại -.- kiểu phải lm lại cái component Image khác dựa theo Image của Nextui rồi lấy props bth của thẻ img, tạo thêm cái props của bên remix-image rồi truyền vào các kiểu, lm đều còn chỉnh type các thứ nữa, k bt đường mà lần luôn -.-

**Comment by ctuanle** [comment]
@Khanhtran47  cực hè, mà t thấy tmdb nó có source resize sẵn rồi mà, vẫn k đủ à

**Comment by Khanhtran47** [comment]
> @Khanhtran47 cực hè, mà t thấy tmdb nó có source resize sẵn rồi mà, vẫn k đủ à

@ctuanle ừ t để lại theo size nhỏ hơn của tmdb rồi đều cái trên hấn tối ưu lại ảnh theo cái khung của mình luôn

**Comment by ctuanle** [comment]
@Khanhtran47 mấy cái tối ưu bên frontend này t chưa mò tới lần nào nên cũng không rành nữa 😅

**Comment by ctuanle** [comment]
@Khanhtran47  mà cái repo remix-image buồn cười phết, mấy cái dev-dependencies nó bỏ vô chung với dependency thường luôn 🦊

**Comment by Khanhtran47** [comment]
@ctuanle kiểu như cái ảnh ni render ra cái khung là 215x340 mà ảnh từ tmdb size là 342x513, cái remix-image nó lm cái server render lại ảnh cho đúng size của khung 

![image](https://user-images.githubusercontent.com/54718468/185243433-70132c0c-485a-4146-a853-6023f045084a.png)

**Comment by Khanhtran47** [comment]
> @Khanhtran47 mà cái repo remix-image buồn cười phết, mấy cái dev-dependencies nó bỏ vô chung với dependency thường luôn 🦊

@ctuanle ừ code chính của cha khác lm mà, thằng ni lấy về lm lại thành cái package thui 

https://gist.github.com/jacob-ebey/3a37a86307de9ef22f47aae2e593b56f

**Comment by ctuanle** [comment]
> kiểu như cái ảnh ni render ra cái khung là 215x340 mà ảnh từ tmdb size là 342x513, cái remix-image nó lm cái server render lại ảnh cho đúng size của khung

@Khanhtran47  ra vậy, mà chắc k sao đâu, lên web xem phim thì phải tính trước là mất nhiều data rồi, cho rõ nét tí mới thích 😅
