### ISSUE TITLE
Detail page: Cast and Crew tab

### ISSUE THREAD

**Issue by Khanhtran47** [Khanhtran47/remix-movie#103]
Already add cast and crew tab in #123 
things left to do:  We have many items from both cast and crew (about 100 → 500 items), so we need to install a package for virtualizing list and use in List component 

https://tanstack.com/virtual/v3/docs/guide/introduction

**Comment by ctuanle** [comment]
@Khanhtran47  cái này m muốn render hết cả mấy trắm người ra á ? t nghĩ k cần thiết lắm đâu, nếu t là người xem chẳng hạn, t quan tâm cỡ 20 - 30 diễn viên đầu là cùng 😅

**Comment by Khanhtran47** [comment]
> @Khanhtran47 cái này m muốn render hết cả mấy trắm người ra á ? t nghĩ k cần thiết lắm đâu, nếu t là người xem chẳng hạn, t quan tâm cỡ 20 - 30 diễn viên đầu là cùng 😅

@ctuanle k nơi, t nghĩ lm kiểu infinite scroll ý, đều thay vì scroll thì add 1 button load more ở dưới, ai muốn xem tiếp thì ấn ý 
với thêm cái virtual phía trên để nó virtual mấy cái đang hiển thị, t định thêm cái infinite scroll ni nơi chỗ search với recommendation phim đồ luôn

**Comment by ctuanle** [comment]
@Khanhtran47  có nghĩa là mấy trăm người đó **được load sẵn rồi**, giờ thay vì render hết 1 lần thì dùng cái "virtual" này để render trước 1 ít rồi lúc scroll mới render tiếp từng đợt á hầy ?

**Comment by Khanhtran47** [comment]
> @Khanhtran47 có nghĩa là mấy trăm người đó **được load sẵn rồi**, giờ thay vì render hết 1 lần thì dùng cái "virtual" này để render trước 1 ít rồi lúc scroll mới render tiếp từng đợt á hầy ?

@ctuanle ừ, kiểu scroll đến mô thì hấn render trong view, mấy cái scroll qua cũng ẩn luôn, theo t hiểu về cái virtual ni là rứa 

có example của remix luôn 🚀
https://github.dev/remix-run/remix/tree/main/examples/infinite-scrolling
