### ISSUE TITLE
bug: Add a default image if we don't have an image of movie, tv, people from data 

### ISSUE THREAD

**Issue by Khanhtran47** [Khanhtran47/remix-movie#122]
![image](https://user-images.githubusercontent.com/54718468/185742436-753ca206-adb9-4752-aff6-01c3aa802b6d.png)

**Comment by Khanhtran47** [comment]
@ctuanle bên diễn viên t thêm cái màu rồi chắc k sao, bên phim đồ rứa thì mình thêm hình chi đây :v 

![image](https://user-images.githubusercontent.com/54718468/190507168-e94d9916-8044-43ef-8f1f-2d47a16a5c8b.png)

**Comment by ctuanle** [comment]
@Khanhtran47 
![image](https://user-images.githubusercontent.com/70543626/190508132-547e4d58-754b-45d5-8d6a-87784982c1cd.png)

kiểu như vậy ? 😅

nơi chỗ mấy cái ảnh poster đồ mà chưa load xong, cái khung mình để cho nó dài hơn đc k ? thấy kiểu nó ngắn ngắn đến khi load ảnh xong thì lại dài ra :v

**Comment by Khanhtran47** [comment]
> nơi chỗ mấy cái ảnh poster đồ mà chưa load xong, cái khung mình để cho nó dài hơn đc k ? thấy kiểu nó ngắn ngắn đến khi load ảnh xong thì lại dài ra :v

@ctuanle ừ do t chưa thêm cái size sẵn cho cái card nên khi loading lazy nó ra cái card có text dưới trc xong có ảnh nó mới to ra
