### ISSUE TITLE
Feature: New UI for MediaList type table 

### ISSUE THREAD

**Issue by Khanhtran47** [Khanhtran47/remix-movie#133]
@ctuanle t nghĩ làm như kiểu của xemphim đẹp 😅 mỗi phim một row rứa luôn, rồi hiển thị thông tin bên trong 

desktop:
![image](https://user-images.githubusercontent.com/54718468/188285646-c751b7f0-da77-4131-9dbf-cf4819985165.png)

mobile: 
![image](https://user-images.githubusercontent.com/54718468/188285779-b996102b-4822-44db-bcf3-70726645904f.png)

hoặc như bên themoviedb, hấn có thêm bo tròn 4 góc với thêm shadow

![image](https://user-images.githubusercontent.com/54718468/188285927-ce7185b2-1e6c-4925-9834-bbcccb406660.png)

**Comment by ctuanle** [comment]
> t nghĩ làm như kiểu của xemphim đẹp 😅 mỗi phim một row rứa luôn, rồi hiển thị thông tin bên trong

@Khanhtran47 ừm nhìn có vẻ đẹp ha
