### ISSUE TITLE
feature: test new api 

### ISSUE THREAD

**Issue by Khanhtran47** [Khanhtran47/remix-movie#136]
@ctuanle 
- [x] loklok (https://documenter.getpostman.com/view/18986031/UVXdNeFD)
- [x] consumet (https://docs.consumet.org/)
	- [x] anilist
	- [x] flixhq
- [x] opensubtitle (https://opensubtitles.stoplight.io/docs/opensubtitles-api/e3750fd63a100-getting-started)

**Comment by ctuanle** [comment]
@Khanhtran47  loklok movie https://loklok.vercel.app/api/movie?name=Fall
search bên tv thấy k ra chi nơi, k biết lộn chộ mô, thấy bên kia nó dùng chung cả movie với tv luôn

mà cái api làm ra rồi dùng kiểu gì, thấy consumet nó có hết r mà 😅

**Comment by Khanhtran47** [comment]
> mà cái api làm ra rồi dùng chỗ mô, thấy consumet nó có hết r mà 😅

@ctuanle thêm sub tiếng việt đồ nữa nơi, bên consumet hấn có mỗi sub tiếng anh thôi

**Comment by ctuanle** [comment]
@Khanhtran47  ra dậy

**Comment by Khanhtran47** [comment]
@ctuanle sao github bữa nay lag vậy, t ấn link pr mà nó nhảy rồi load lung tung luôn 🥲

**Comment by ctuanle** [comment]
@Khanhtran47  rứa á ? t thấy bth mà ta 😅

**Comment by Khanhtran47** [comment]
bên tv thấy k ra chi nơi, k biết lộn chộ mô, thấy bên kia nó dùng chung cả movie với tv luôn

@ctuanle ừ kiểu k có xem để chỉnh đc nên hơi khó -.-  hấn chia theo dramaType 🤣

**Comment by ctuanle** [comment]
@Khanhtran47  ồ, để t thử xem có ra gì k

**Comment by ctuanle** [comment]
@Khanhtran47 đúng là bên cái movie detail thì tv series phải bỏ category=1 mới ra, đều bên search chả biết bỏ gì luôn, có mấy bộ nổi thì ra, có bộ k ra,

**Comment by Khanhtran47** [comment]
> @Khanhtran47 đúng là bên cái movie detail thì tv series phải bỏ category=1 mới ra, đều bên search chả biết bỏ gì luôn, có mấy bộ nổi thì ra, có bộ k ra,

@ctuanle éc, search anime đồ có ra k, search theo tên tiếng anh ý

**Comment by Khanhtran47** [comment]
@ctuanle t thấy ra đc mà 🤣 mấy bộ k nổi thì chịu thui hoặc bên kia để tên khác hoặc hấn chia part khác nhau như hunter đó tự nhiên chia ra mấy phần lận 🥲

![image](https://user-images.githubusercontent.com/54718468/194728386-6fe548b1-8a69-43d5-befb-09190c8a346a.png)
![image](https://user-images.githubusercontent.com/54718468/194728421-c1a26e60-453a-416f-b805-9dd1890c4e1c.png)

**Comment by ctuanle** [comment]
@Khanhtran47 ừm anime thì dễ ra hơn kìa, nãy t thử search mấy cái tv show có cái ra cái k

**Comment by Khanhtran47** [comment]
> @Khanhtran47 ừm anime thì dễ ra hơn kìa, nãy t thử search mấy cái tv show có cái ra cái k

@ctuanle tv show k có thì chắc chịu khó search subtitle bên open subtitles t nghĩ chắc có 🥲 anime thì mới cần sub bên loklok thui

**Comment by ctuanle** [comment]
@Khanhtran47  ừm mà anime nó cũng chia season đồ tìm hơi cực :v

**Comment by Khanhtran47** [comment]
@ctuanle bên loklok rứa là xong rồi chi, m viết file services bên ni luôn đk 😅 chbi qua tv show với anime mò tiếp 🥲
