### ISSUE TITLE
feat: watch history page in left drawer

### ISSUE THREAD

**Issue by Khanhtran47** [Khanhtran47/remix-movie#152]
- [ ] local mode, no auth (with indexdb ?)
- [ ] from remote db, with auth

@ctuanle 
UI from netflix

![image](https://user-images.githubusercontent.com/54718468/195922608-62f9e704-7697-4880-a1e5-9ff55eb85cc5.png)
![image](https://user-images.githubusercontent.com/54718468/195922766-67880c87-6654-48f3-a1d7-3cf42bb30f98.png)
maybe add a x button for deleting item ?

How should we define a watched item ? Clicked play button ?
- after clicking play button from watch page (https://artplayer.org/document/events#play), this event can access from getInstance props 

![image](https://user-images.githubusercontent.com/54718468/195922014-1e9960d4-612a-482b-8ed4-0e49130dae02.png)

Info to save ?
- id: movieId for movies, tvId, seasonId, episodeId for tv-shows, animeId, episodeId for anime (we can fetch episode image or movie image for building UI)
- duration
- watch route (/movies/id/watch or /tv-shows/84773/season/1/episode/1 or /anime/127230/episode/chainsaw-man-episode-1) 
- time and date watched: we can get and set currentTime for [artplayer](https://artplayer.org/document/propertie#currenttime), but artplayer has a continued playing video feature built-in itself, it stores time watched in local storage, but id is the link of played file 🥲 maybe we can add our own id by [this](https://artplayer.org/document/events#destroy) after player is destroyed and [this](https://artplayer.org/document/advance#storage).

![image](https://user-images.githubusercontent.com/54718468/195921711-74e4a095-0a2f-480d-b2cf-3ddce5b08e18.png)

- ...

**Comment by Khanhtran47** [comment]
@ctuanle cái ni lưu vô localstorage hay lưu lên supabase hậy ?

**Comment by ctuanle** [comment]
> @ctuanle t nghĩ là nếu chưa đăng nhập thì lưu trên localStorage, còn nếu đăng nhập rồi thì lấy data từ database

@Khanhtran47  ừm vậy cũng tiện

**Comment by Khanhtran47** [comment]
@ctuanle cái ni m lm đk ? 😅

**Comment by ctuanle** [comment]
@Khanhtran47  idk, m có muốn làm thì làm đi k cần chừa cho t đâu 😅

**Comment by Khanhtran47** [comment]
@ctuanle này t chưa lm nơi, t đang lm mấy cái bên player đồ rứa, m lm đc cái ni thì lm 🥲 k thì để rứa sau t lm

**Comment by ctuanle** [comment]
@Khanhtran47 okay 😅, will try
