### ISSUE TITLE
Detail page: Movie, Tv show, Anime

### ISSUE THREAD

**Issue by Khanhtran47** [Khanhtran47/remix-movie#16]
- [ ] add movie picture, description, banner, genre, cast, director (if available)
- [ ] add similar movies
- [ ] add link embedded for movie 👍 

```
[
        {
            "name": "123movies",
            "url": "https://googlvideo.com/"
        },
        { 
            "name": "2Embed",
            "url": "https://www.2embed.to/"
        },
        { 
            "name": "2Embed",
            "url": "https://2embed.org/"
        },
        {
            "name": "APIMovieDB",
            "url": "https://v2.apimdb.net/"
        },
        {
            "name": "DBGDrivePlayer",
            "url": "https://databasegdriveplayer.co/"
        },
        {
            "name": "DBGo",
            "url": "https://dbgo.fun/"
        },
        {
            "name": "FireSonic",
            "url": "https://firesonic.sc/play_video.php?video_id={imdbId}"
        },
        {
            "name": "Free Streaming API",
            "url": "https://fsapi.xyz/"
        },
        {
            "name": "GOMO",
            "url": "https://gomo.to/movie/{imdbId}"
        },
        {
            "name": "VidSource",
            "url": "https://vidsrc.me/"
        },
        {
            "name": "Superembed",
            "url": "https://www.superembed.stream/"
        },
        {
            "name": "Databasegdriveplayer",
            "url": "https://databasegdriveplayer.co/player.php?tmdb={TMDb_ID}"
        },
        {
            "name": "Autoembed",
            "url": "https://autoembed.xyz/"
        },
        {
            "name": "1movietv",
            "url": "https://1movietv.com/"
        },
        {
            "name": "Gdriveplayer",
            "url": "https://api.gdriveplayer.us/"
        },
        {
            "name": "Streamo",
            "url": "https://streamo.cc/"
        },
        {
            "name": "123movie",
            "url": "https://api.123movie.cc/"
        }
]
```

- [ ] features after finishing authentication 🤟

**Comment by Khanhtran47** [comment]
@ctuanle từng này api mình lm cái khu trung tâm giải trí tổng hợp cũng đc ấy :v kiếm thêm api manga đồ các kiểu bỏ vô luôn ✌️ 
t mới check vài api có anime 1080p, phụ đề tiếng anh hết luôn mà kho tầm hơn 8k bộ

**Comment by Khanhtran47** [comment]
https://ophim.tv/api-document source vietsub đều xài api hơi khó tại phải có tên phim bằng tiếng việt :v

**Comment by ctuanle** [comment]
Nó sử dụng hệ thống id khác mình mà lại còn tiêu đề tiếng việt nữa 😅

**Comment by Khanhtran47** [comment]
> Nó sử dụng hệ thống id khác mình mà lại còn tiêu đề tiếng việt nữa 😅

@ctuanle ừ sau bí quá thì chia ra 2 route en với vi :v

**Comment by Khanhtran47** [comment]
@ctuanle 
bugs: 

- xài dark reader hoặc adguard => trang break, k có style (bị sau khi t update react 18 với remix latest)
- player 1 xài ok, player 2, 3 xem đc trên localhost => trên trang chính thì player 2 nó cho xem qc :v player 3 thì bị chặn, sau thêm cái sandbox chặn mở popup đồ các kiểu ( t test mà nó cho qc nhiều vl ), allow full screen cho iframe 

![image](https://user-images.githubusercontent.com/54718468/180752860-ded6f26a-4d0c-4226-b875-2c4ddf8f6f79.png)

- responsive
- hoàn thành trang detail

![image](https://user-images.githubusercontent.com/54718468/180753137-abd58210-2153-48c4-9b3c-6938f99dbcdc.png)

- hoàn thành trang xem phim (trang tv thì thêm chuyển season với chuyển tập, player 2 của trang xem tv k có id imdb trong detail của phim :( )

**Comment by Khanhtran47** [comment]
bug 2: player 3 bị chặn https://stackoverflow.com/questions/67765238/mixed-content-the-page-at-was-loaded-over-https-but-requested-an-insecure-resour

**Comment by ctuanle** [comment]
@Khanhtran47 

> 1. xài dark reader hoặc adguard => trang break,

ừm t xài uBlock nó cx bị lỗi style, k xài chặn q.cáo thì qc nhiều vl :v

**Comment by Khanhtran47** [comment]
> @Khanhtran47 
> 
> > 1. xài dark reader hoặc adguard => trang break,
> 
> ừm t xài uBlock nó cx bị lỗi style, k xài chặn q.cáo thì qc nhiều vl :v 
> 

@ctuanle ừ t kiểu update react xong local chạy bth sau build lên thì bị rứa, k hiểu do đâu luôn

**Comment by Khanhtran47** [comment]
@ctuanle thôi fix dần rồi merge sau :v

**Comment by Khanhtran47** [comment]
@ctuanle t tạo 1 đống issue rứa, m thích lm cái mô thì assigne nha
