### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by Khanhtran47** [Khanhtran47/remix-movie#20]
https://remix.run/docs/en/v1/guides/routing
@ctuanle m nghiên cứu cái ni thử, t đọc qua mà k chắc có đúng k nữa 

- index.tsx
- trending.tsx
- recommend.tsx
- recent.tsx
- top-imdb.tsx
- history.tsx
- movies
    - /index.tsx        (render a list of movies)
    - /$moviesId.tsx (theo t hiểu thì mỗi id film thì ứng với file như ri)
- tv-shows
    - /index.tsx
    - $tvId.tsx
- animes
	- $animesId.tsx
	- index.tsx (xài api của mal)
- __auth
	- login.tsx
	- signup.tsx 
- __auth.jsx (này t k chắc)

**Comment by ctuanle** [comment]
@Khanhtran47  như này thì sao ?
thay vì **list-movies** thì chỉ cần **/movies** thôi (này render list), còn **/movies/$id** thì render trang film

**Comment by Khanhtran47** [comment]
> @Khanhtran47  như này thì sao ?
> thay vì **list-movies** thì chỉ cần **/movies** thôi (này render list), còn **/movies/$id** thì render trang film

ừ m xem sửa cho hợp lý t với, t mới đọc qua k code k hình dung đc nơi 😅

**Comment by ctuanle** [comment]
@Khanhtran47  t thấy làm như răng cũng được, kiểu như m viết đó cũng ổn.

Đều thường họ làm kiểu 
- **/models** (số nhiều, nếu không có chi thêm thì render 1 list như vậy), rồi kiểu sâu hơn nữa thì như 
- **/models/id** thì render 1 trang detail, 
- **/models?name=Khanh&rate=9.0** bla bla thì filter đồ rứa, rồi như 
- **/movies/$id/credits** như bên cái **react-movie-app** của m chẳng hạn, kiểu theo chiều sâu như vậy

**Comment by Khanhtran47** [comment]
@ctuanle m edit nơi description luôn đi

**Comment by Khanhtran47** [comment]
@ctuanle à t nghĩ mấy cái list chắc tống vô 1 thư mục _list đc 😀

**Comment by ctuanle** [comment]
@Khanhtran47  ừm, okay. mà mấy cái __ ở đầu là gì vậy :v ?

**Comment by Khanhtran47** [comment]
@ctuanle á t quên nơi chỗ mà `<Link href={}  />` của từng phim trong trending, sau thay bằng `<Link to={} />` để nó khỏi load lại trang khi chuyển

**Comment by ctuanle** [comment]
@Khanhtran47 

> á t quên nơi chỗ mà `<Link href={} />` của từng phim trong trending, sau thay bằng `<Link to={} />` để nó khỏi load lại trang khi chuyển

ồ, t cũng k để ý là nó có load lại trang luôn kìa :v 



> mà bữa ni t hơi bận tý nên k code đc mấy nơi :v m lm chill chill thôi, đợi t xong soutenance t cày :v

okay

**Comment by ctuanle** [comment]
@Khanhtran47  cái này hình như xong rồi phải k ?

**Comment by Khanhtran47** [comment]
@ctuanle ừ để t close
