### ISSUE TITLE
perf: cache/persist request results to reduce number of requests/ waiting time

### ISSUE THREAD

**Issue by ctuanle** [Khanhtran47/remix-movie#200]
- [x] in-memory caching #205 
- [x] optional cache (env.LRU_CACHE=false for ex) #221 
- [x] <del>persist id mapping (tmdbid -> loklokId for ex)</del> not really needed

**Comment by Khanhtran47** [comment]
@ctuanle t k hiểu nơi 😅

**Comment by ctuanle** [comment]
@Khanhtran47 😅 ý tưởng nhất thời thôi, nhưng t thấy cũng thú vị, cache-server. 
kiểu như bên trình duyệt nó hay cache mấy content như ảnh với css đồ để đỡ phải load lại thì bên server cũng làm tương tự được, thậm chí mình có thể cải thiện cache ở phía browser theo cách mình nữa.

mấy routes mà chỉ cần gửi 1 request thôi như popular hay top-rated thì k nói, nhưng như mấy routes movieid.watch chẳng hạn, nó gọi tầm 4, 5 request liền nhau, thay vì lần nào cũng phải gọi 4, 5 request như vậy thì mình lưu kết quả lại (kiểu key-value như tmdb-id -> kết quả, sợ bị out-dated thì lưu cỡ 1 ngày hay gì đó thôi). 

mặc dù nó thêm 1 bước trung gian, nhưng tổng thể có thể giảm đc kha khá request. ví dụ 10 client khác nhau cùng xem phim thor thì :
- client1 gọi thor.watch, chưa có cache, 1 req hỏi cache chưa + 4 request lấy dữ liệu + 1 task cache (cỡ 1 req) => 6 req
- client 2 gọi thor.watch, có cache rồi => 1 req lấy cached
- client 3, 4, 4 ... tương tự
tổng cộng mình chỉ gọi 15 request thay vì 10*4 = 40 khi k có cache, t nghĩ cũng thú vị 

giải pháp thì chắc redis hay firebase gì đó vừa free vừa nhanh, k biết supabase có kiểu lưu cache k.

**Comment by ctuanle** [comment]
@Khanhtran47 mới ý tưởng thôi 😅, đều để t làm thử
