### ISSUE TITLE
Supabase Sql table generator file?

### ISSUE THREAD

**Issue by animemandir** [Khanhtran47/remix-movie#229]
If you don't mind, I'd like to see ho you made the supabase sql tables.

**Comment by ctuanle** [comment]
@animemandir  Thank you for your interest in our project. 
There is nothing complicated about our database, though. We currently only have one simple table for history records, and for user management we use the built-in Authentication function of supabase.
Here is the sql to generate the History table:

```sql
create table histories (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid not null,
  media_type varchar not null,
  media_id varchar not null,
  duration bigint not null,
  title varchar,
  route varchar not null,
  watched bigint,
  poster varchar,
  overview text,
  season varchar,
  episode varchar
);
```
