### ISSUE TITLE
Need to merge movies with the same id ? 

### ISSUE THREAD

**Issue by Khanhtran47** [Khanhtran47/remix-movie#233]
@ctuanle t nghĩ mấy phim có id rồi thì đè data lên đk ? 

![image](https://user-images.githubusercontent.com/54718468/198893915-ca8fbf37-d373-4af4-ab4a-317c5187266f.png)

**Comment by ctuanle** [comment]
@Khanhtran47 t nhớ t chỉnh cho nó k trùng rồi mà. mấy cái này lâu chưa ? m thử xem mấy cái khác coi thử có trùng không, nhiều lúc dữ liệu cũ t chưa xóa.

**Comment by Khanhtran47** [comment]
@ctuanle t mới xem hôm qua với lúc sáng nơi 

![image](https://user-images.githubusercontent.com/54718468/198894969-c2a061c1-93f2-4eef-bbdc-80b23d244cc6.png)

**Comment by ctuanle** [comment]
@Khanhtran47 ừm để chút t thử lại

**Comment by ctuanle** [comment]
@Khanhtran47  tv với anime thì m muốn răng, khác season, episode nhưng cùng id có gộp k ?

**Comment by Khanhtran47** [comment]
> @Khanhtran47 tv với anime thì m muốn răng, khác season, episode nhưng cùng id có gộp k ?
> 
> supabase không so sánh null == null được :v nên lúc so sánh movie mà không có season với episode nó cho ra khác nhau cả :v

@ctuanle ừ với tv anime đồ thì chia season với episode ra thôi
