### ISSUE TITLE
load css - add a loader

### ISSUE THREAD

**Issue by Khanhtran47** [Khanhtran47/remix-movie#25]
@ctuanle Maybe add a loader for hiding this :v 

![image](https://user-images.githubusercontent.com/54718468/174456543-40e155e8-b0d2-4580-820f-50ac660a38e0.png)

**Comment by ctuanle** [comment]
@Khanhtran47 nếu không nhầm thì trang ni trang chủ phải k, trang này có load gì đâu. Mà cũng thấy lạ sao nó lại có kiểu giống chưa load xong css ấy nhỉ.
Phần nơi ảnh hình như lúc click chuyển sang trang mình chưa làm rồi trở về trang trước là nó bị phải không ? Sau mình thêm code cho mấy trang đó t nghĩ chắc nó tự hết thôi :v

**Comment by Khanhtran47** [comment]
@ctuanle ừ kiểu có code của tailwindcss đó, m nhìn nơi header vẫn có display flex đồ, cái ni do bên load nextui với stitches

**Comment by ctuanle** [comment]
@Khanhtran47 thế giới UI thật lắm sắc màu 🥴

**Comment by Khanhtran47** [comment]
@ctuanle hay setup theo cái example của bên remix https://github.com/remix-run/remix/tree/dev/examples/stitches

**Comment by ctuanle** [comment]
@Khanhtran47  ừm rứa cx đc 😅

**Comment by Khanhtran47** [comment]
@ctuanle t k chắc là đc k đều cứ thử xem sao

**Comment by Khanhtran47** [comment]
@ctuanle chắc cái layout rứa là xong rồi 🥲 còn hơi lỗi đều ok đk :v 
h chắc bắt đầu lm mấy cái page khác thôi

**Comment by Khanhtran47** [comment]
@ctuanle do nextui chưa sup ssr nên cái web mình bị như vậy :v hiện tại mình cần thêm 1 cái theme provider hoặc đợi nextui fix :v
https://github.com/nextui-org/nextui/discussions/286

**Comment by Khanhtran47** [comment]
@ctuanle t định tạo 1 cái animtion khi bắt đầu load trang chứ k hiểu sao t thêm base css cho nextui rồi mà đôi khi vẫn thấy k style nơi -_-

**Comment by Khanhtran47** [comment]
@ctuanle 
https://lottiefiles.com/search?q=movie&category=animations&animations-page=1

**Comment by ctuanle** [comment]
> https://lottiefiles.com/search?q=movie&category=animations&animations-page=1

ồ, nhiều cái hay nhỉ

**Comment by ctuanle** [comment]
@Khanhtran47 

> t định tạo 1 cái animtion khi bắt đầu load trang chứ k hiểu sao t thêm base css cho nextui rồi mà đôi khi vẫn thấy k style nơi -_-

có cách nào để biết khi nào nó load xong không, hay là cứ bỏ đại cái animation vài giấy rứa :v

**Comment by Khanhtran47** [comment]
> @Khanhtran47
> 
> > t định tạo 1 cái animtion khi bắt đầu load trang chứ k hiểu sao t thêm base css cho nextui rồi mà đôi khi vẫn thấy k style nơi -_-
> 
> có cách nào để biết khi nào nó load xong không, hay là cứ bỏ đại cái animation vài giây rứa :v t thấy nó chia ra 3 giai đoạn:
> 
> * đoạn chưa có css nhìn chưa ra form (1s ?)

ừ đoạn ni t cũng k rõ, kiểu t cop lại nguyên code của bên example của nextui rồi mà vẫn bị, đều đỡ hơn hồi trc 
> * đoạn có css rồi nhưng vẫn light mode (0.5s ?) (nếu chọn light mode thì k có đoạn chuyển từ light sang dark)

đoạn ni là do cái custom theme của bên nextui chưa hỗ trợ ssr, t xài next themes để lm cái provider theme khi load nớ đều nhanh hơn nhưng nhìn vẫn thấy 
> * đoạn dark mode (xong)
