### ISSUE TITLE
style page not found + error page

### ISSUE THREAD

**Issue by Khanhtran47** [Khanhtran47/remix-movie#34]
style lại trang 404 với error, thêm nút để chuyển về trang chủ 

- [ ] tạo component errorboundary + catchboundary

https://remix.run/docs/en/v1/api/conventions#catchboundary
https://remix.run/docs/en/v1/api/conventions#errorboundary
https://remix.run/docs/en/v1/guides/not-found
https://remix.run/docs/en/v1/guides/errors

![image](https://user-images.githubusercontent.com/54718468/175305802-4d4cc289-ba71-40cf-9255-b67640ed89b8.png)

**Comment by ctuanle** [comment]
@Khanhtran47 phần ni t thấy m làm trang Not Found rồi. 
Chắc t làm tiếp để nó catch mấy cái [ID phim bị sai](https://remix-watchmovie.vercel.app/moviess/6160374bla) 
![image](https://user-images.githubusercontent.com/70543626/181450262-18a9582c-a81a-4f6d-8e21-9adf75fa8bf8.png)

**Comment by Khanhtran47** [comment]
@ctuanle ừ phần id not found chưa có 
với t kb sao mỗi lần kiểu có lỗi sau chuyển qua trang not found đồ các kiểu là cũng k có style :( phải reset trang lại mới có

**Comment by ctuanle** [comment]
@Khanhtran47  t cũng k rõ nưa, nhưng t nghĩ do cái CatchBoundary nó nằm ngoài cái App ?
Để t thử thêm 1 cái ở trong index.tsx thử

**Comment by Khanhtran47** [comment]
@ctuanle t nghĩ là cái nằm ngoài App thì style bằng tailwindcss còn cái bên trong thì để bth xài nextui được rồi
