### ISSUE TITLE
Add watch trailer modal when click watch trailer

### ISSUE THREAD

**Issue by Khanhtran47** [Khanhtran47/remix-movie#58]
https://nextui.org/docs/components/modal

**Comment by Khanhtran47** [comment]
@ctuanle xem trailer chắc lm theo kiểu của netflix :3 
https://github.com/Gyanreyer/react-hover-video-player

**Comment by ctuanle** [comment]
> mà k bt cái embed của bên youtube như nào nữa

ý m là nói embed của youtube nói chung hay sao ? t nhớ bên repo react-movie-app có dùng thì phải

**Comment by Khanhtran47** [comment]
> > mà k bt cái embed của bên youtube như nào nữa
> 
> @Khanhtran47 ý m là nói embed của youtube nói chung hay sao ? t nhớ bên repo react-movie-app có dùng thì phải

@ctuanle ừ đều t k bt hấn có xài đc với cái thư viện trên k, để khi mô code test thử

**Comment by Khanhtran47** [comment]
@ctuanle 
t thử ấn let's go -> hình 1
sau chuyển thành sort by average -> hình 2
chuyển lại popularity -> hình 3

![image](https://user-images.githubusercontent.com/54718468/183308839-50ff18e9-a714-412f-b467-b0bdfdff1129.png)

![image](https://user-images.githubusercontent.com/54718468/183308850-93fdc60f-fe24-4f74-9615-9216d1e12169.png)

![image](https://user-images.githubusercontent.com/54718468/183308865-2f070704-0fd4-4973-926a-1f1cda55a038.png)

k bt sao nó filter ra toàn mấy phim gì gì ấy 😶‍🌫️

**Comment by Khanhtran47** [comment]
@ctuanle à t hiểu rồi, bên popularity sai chính tả, thiếu chữ t 
bên top rated, m cho thêm minimum user votes tầm hơn 200-300 cho chính xác

**Comment by Khanhtran47** [comment]
@ctuanle với có bug kiểu ni, khi mà filter xong sau qua route filter thì cái select nó có chọn genre đều trên value thì nó hiện là All, sau t chọn genre khác thì hấn bị lỗi 

![image](https://user-images.githubusercontent.com/54718468/183309342-41a5b5c6-409d-4d6f-ba75-006474a9ed69.png)

**Comment by Khanhtran47** [comment]
@ctuanle đậu mé t cmt sai nơi -.-
