### ISSUE TITLE
Add select season and episode for watch tv 

### ISSUE THREAD

**Issue by Khanhtran47** [Khanhtran47/remix-movie#64]
@ctuanle player 2 cần id của imdb đều api detail của tvshow từ tmdb k có id imdb nên t k biết lấy kiểu gì, 1 là nghĩ cách lấy id imdb 2 là lm cái điều kiện xóa player 2 của tv show

**Comment by ctuanle** [comment]
@Khanhtran47 

[tv/get-tv-external-ids](https://developers.themoviedb.org/3/tv/get-tv-external-ids)
![image](https://user-images.githubusercontent.com/70543626/181189616-ab2a3af2-7d5b-49e1-a61e-15fb7749b48f.png)

chắc là cái này

**Comment by ctuanle** [comment]
@Khanhtran47  should work now 🐳
https://remix-movie-git-feature-34-khanhtran47.vercel.app/tv-shows/watch/197067

**Comment by Khanhtran47** [comment]
@ctuanle ừ cái player 2 nhiều film có tự động chọn sub từ open subtitle nên có tiếng việt :3
