### ISSUE TITLE
feat: add meta for every route 

### ISSUE THREAD

**Issue by Khanhtran47** [Khanhtran47/remix-movie#73]
Example: title should be List movies instead of Remix App

![image](https://user-images.githubusercontent.com/54718468/182424144-c2404e2e-bd60-4a2c-938a-bae4f0c452b3.png)

**Comment by Khanhtran47** [comment]
@ctuanle m bt chi về SEO k :v

**Comment by ctuanle** [comment]
@Khanhtran47  

> m bt chi về SEO k :v

k biết nơi, chắc mấy mẹo để xuất hiện trên tìm kiếm à

![image](https://user-images.githubusercontent.com/70543626/192593401-07d07f58-c5f3-4b40-a652-5e2ea933639a.png)

> với mình xài data từ loader trong meta function đk hậy ?

chắc đc
https://remix.run/docs/en/v1/api/conventions#page-context-in-meta-function

**Comment by Khanhtran47** [comment]
> k biết nơi, chắc mấy mẹo để xuất hiện trên tìm kiếm à
@ctuanle ừ kiểu mấy thẻ meta để SEO đồ rứa chắc search gg có, hồi xưa t đọc đc blog mô đó cho bên next

**Comment by ctuanle** [comment]
@Khanhtran47 

![image](https://user-images.githubusercontent.com/70543626/192596955-d3cef37a-ad92-4a5c-847d-a4746935ce27.png)

gõ cả tên app ra mà k hiện trên gg search luôn :v

**Comment by Khanhtran47** [comment]
> gõ cả tên app ra mà k hiện trên gg search luôn :v

@ctuanle do mình đã thêm thẻ meta chi mô 😅 trang mô cũng remix app rứa thui :v

**Comment by ctuanle** [comment]
> do mình đã thêm thẻ meta chi mô 😅 trang mô cũng remix app rứa thui :v

@Khanhtran47 😅

**Comment by Khanhtran47** [comment]
@ctuanle 

![58c1ae4ed23e4fab2a2c69ec6c9a460011de05c5_s2_n1](https://user-images.githubusercontent.com/54718468/195374238-3b1ffc8e-9ee7-49ae-8b40-d37268cc2744.png)
![86b797da628d84b8bc3e14b44ad0b9283fdd50ca_s2_n1](https://user-images.githubusercontent.com/54718468/195374246-b08b05c6-c479-44c5-8c87-0dabef03374b.png)
![ff1e9d4317f10ccee40044dc3d6c384385864fcc_s2_n1](https://user-images.githubusercontent.com/54718468/195374249-baa6a4d9-cada-4731-ab52-1b757e8ee309.png)
![f0a2cb11b5bde22fe62f1b5829a94c9def7ab9d0_s2_n1](https://user-images.githubusercontent.com/54718468/195374253-fb6c0b2b-0d3a-4456-988a-39741863b0e9.png)
![b16342e022642e21317f8588d1207e57f82ff4c0_s2_n1](https://user-images.githubusercontent.com/54718468/195374258-866e975e-5c1e-479a-8289-e910c1293e57.png)
![e7951fb7f060ed4adc6258ad94d4ca5a260aeb76_s2_n1](https://user-images.githubusercontent.com/54718468/195374263-7549e866-feb7-43a3-9b67-9def58492e40.png)
![ad5542bdc6f6086d3b5b86a0e7bf03186187d044_s2_n1](https://user-images.githubusercontent.com/54718468/195374271-50260db3-797a-4f81-9238-0444c7a3d198.png)
![9db0ecb88234625850d9161ac020d44ab47c5658_s2_n1](https://user-images.githubusercontent.com/54718468/195374278-88587b5b-ef31-4361-aa35-a945e3d69cbe.png)
![ac9731476fd11f8ae204dc3c5ab958f324ebe1b6_s2_n1](https://user-images.githubusercontent.com/54718468/195374197-f4447cad-ecbf-4849-bbeb-4dc5cad15bb0.png)
![97eeaefe52a2e6087a9e78aecee9812d1a6e828a_s2_n1](https://user-images.githubusercontent.com/54718468/195374205-9d6ed535-655e-4c78-9db1-1a6428d1c184.png)
![c22081b1a92146b4bc0494e1a85fa7411b27f289_s2_n1](https://user-images.githubusercontent.com/54718468/195374208-e5723a38-091f-45e6-a831-1c22f6de7f7e.png)
![ade981b450c12f0ca942f6221029a6885ecb8689_s2_n1](https://user-images.githubusercontent.com/54718468/195374211-6e33086c-1140-4028-8e19-b9b578377451.png)
![e61da748b7c2fc438a2538004eb8cd5813ecf8e4_s2_n1](https://user-images.githubusercontent.com/54718468/195374216-63896690-a40b-4ca2-8e11-75a879c6fda3.png)
![e2099cc9aede76344fbafc66db38c37191e13cda_s2_n1](https://user-images.githubusercontent.com/54718468/195374219-ccc42c77-282f-49c8-954d-54da566f5a6d.png)
![1da9e912bfa106653e696d9bdf8607528f8c593f_s2_n1](https://user-images.githubusercontent.com/54718468/195374222-e7eab5a4-c48b-4ba6-bb17-051572cb8fa7.png)
![e70285fcc0d851b47a7402738e83c4356a70946d_s2_n1](https://user-images.githubusercontent.com/54718468/195374229-fd3f19ec-d33e-4fac-a405-bd4eb5e2d2d7.png)
![2465f69ed0af8aa528a6cd1cbed12499c67e2304_s2_n1](https://user-images.githubusercontent.com/54718468/195374232-8e7b99e8-1551-4580-a90f-af8e5f4324d7.png)
![636bfb9abc5bc3f65eaec787fc71568d02f77c69_s2_n1](https://user-images.githubusercontent.com/54718468/195374236-84598a39-87dd-40c3-8994-03807ad02b8a.png)
![3206c95252522651b473b07968ef55c835aa1123_s2_n1](https://user-images.githubusercontent.com/54718468/195374288-29aaa1a0-9854-4610-b749-33390c63e479.png)
![5c7f92bb4c3181b136fb9c7d2bdcb37092c6dbb2_s2_n1](https://user-images.githubusercontent.com/54718468/195374290-cbc6ca43-cd71-4b74-9014-849839a993e8.png)
