### ISSUE TITLE
Discover page

### ISSUE THREAD

**Issue by Khanhtran47** [Khanhtran47/remix-movie#74]
@ctuanle Filter movie and tv with discover api 

https://developers.themoviedb.org/3/discover/movie-discover
https://developers.themoviedb.org/3/discover/tv-discover

**Comment by Khanhtran47** [comment]
TODO for filter component: add select year, user score, runtime

**Comment by Khanhtran47** [comment]
@ctuanle m thử lm cái filter ni nha, t qua lm bên cái search

**Comment by ctuanle** [comment]
> @ctuanle m thử lm cái filter ni nha, t qua lm bên cái search

gọi api á ?

**Comment by Khanhtran47** [comment]
> > @ctuanle m thử lm cái filter ni nha, t qua lm bên cái search
> 
> @Khanhtran47 gọi api á ?

@ctuanle ừ call api, kiểu thay mấy cái query của link url fetch, t nghĩ là xài useFetcher của remix đồ để call lại

**Comment by ctuanle** [comment]
> @ctuanle ừ call api (thay api movie list hiện tại bằng api discover movie đồ rứa sau thay mấy cái query của link url fetch để filter), t nghĩ là xài useFetcher của remix đồ để call lại, mé hơi rắc rối thiệt -.-

@Khanhtran47  okay để t thử 🤖

**Comment by Khanhtran47** [comment]
> > @ctuanle ừ call api (thay api movie list hiện tại bằng api discover movie đồ rứa sau thay mấy cái query của link url fetch để filter), t nghĩ là xài useFetcher của remix đồ để call lại, mé hơi rắc rối thiệt -.-
> 
> @Khanhtran47 okay để t thử 🤖

@ctuanle hoặc khi filter thì m chuyển route sang 1 trang index ứng với cái filter luôn, k bt đk

**Comment by Khanhtran47** [comment]
@ctuanle à cái select từ cái dropdown lấy value hơi ngu tý 😅
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/values

**Comment by ctuanle** [comment]
> hoặc khi filter thì m chuyển route sang 1 trang index ứng với cái filter luôn, k bt đk

@Khanhtran47  trang index ở đây là gì nhỉ, như movies/discover?filter_query_bla  hay movies/index



> à cái select từ cái dropdown lấy value hơi ngu tý 😅

😅

**Comment by Khanhtran47** [comment]
> > hoặc khi filter thì m chuyển route sang 1 trang index ứng với cái filter luôn, k bt đk
> 
> @Khanhtran47 trang index ở đây là gì nhỉ, như movies/discover?filter_query_bla hay movies/index
> 
> > à cái select từ cái dropdown lấy value hơi ngu tý 😅
> 
> 😅

@ctuanle kiểu movies/discover?sort=...?genre=...?...=... dạng rứa nếu m chuyển route còn muốn giữ nguyên route thì xài useFetcher

**Comment by ctuanle** [comment]
@Khanhtran47 oke
