### ISSUE TITLE
Add multi-language 

### ISSUE THREAD

**Issue by Khanhtran47** [Khanhtran47/remix-movie#84]
Test with French 
https://github.com/sergiodxa/remix-i18next

**Comment by Khanhtran47** [comment]
@ctuanle t mới thêm option language trong api đồ rồi, t nghĩ chắc chuyển language đồ các kiểu đc
với tiếng việt ý, t nghĩ xài api bên ophim đều t k bt để route riêng là vi đồ rứa hay là chuyển ngôn ngữ bth như ri -.-

**Comment by ctuanle** [comment]
> t mới thêm option language trong api đồ rồi

@Khanhtran47 api của tmdb á ?



> với tiếng việt ý, t nghĩ xài api bên ophim đều t k bt để route riêng là vi đồ rứa hay là chuyển ngôn ngữ bth như ri -.-

thấy tmdb cũng có tiếng việt này 

mà ophim gọi api k cần key à :v, tiện nhỉ, đều vậy rồi có dễ chết k biết 😅

**Comment by Khanhtran47** [comment]
> @Khanhtran47 api của tmdb á ?

ừ t bỏ thêm option language cho mấy cái api của tmdb, thêm mấy cái như include_adult rồi region, year các thứ, bữa sau lm search thêm, bên discover m mới lm thì t chưa thêm kịp nơi 

> thấy tmdb cũng có tiếng việt này

ừ đều cái api bên tmdb nó k khớp tên với bên ophim nơi :v 

> mà ophim gọi api k cần key à :v, tiện nhỉ, đều vậy rồi có dễ chết k biết 😅

t định fetch lại từ mấy cái api của nextjs từ trang chủ của [ophim ](https://ophim.tv/) luôn có filter các kiểu :v

**Comment by ctuanle** [comment]
> hoặc m bt cào api thì cào hết đống api rồi tự lm api riêng :v

@Khanhtran47 chịu 😅, t k biết nơi
